# Generated by Django 3.0.4 on 2020-04-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioOptimization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Share', models.CharField(max_length=100)),
            ],
        ),
    ]
