# Generated by Django 3.0.4 on 2020-04-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharevaluelr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sharevaluecalculate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Openingvalue', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='sharevalue',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
