# Generated by Django 3.0.4 on 2020-04-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharevaluelr', '0003_auto_20200421_2054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sharevalue',
        ),
    ]
