# Generated by Django 3.0.4 on 2020-04-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0005_shares'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncShares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='sharesheld',
            name='Name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sharesheld',
            name='Quantity',
            field=models.FloatField(),
        ),
    ]
