# Generated by Django 3.0.4 on 2020-04-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0006_auto_20200420_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharesheld',
            name='Quantity',
            field=models.BigIntegerField(),
        ),
    ]
